cache:
  yarn: true
  directories:
    - $HOME/cache
    - $HOME/.m2
services:
  - mysql
  - postgresql
matrix:
  include:
    - env: OPENRASP_LANG=java SERVER=jboss7
      language: java
      jdk: openjdk8
    - env: OPENRASP_LANG=java SERVER=wildfly8
      language: java
      jdk: openjdk8
    - env: OPENRASP_LANG=java SERVER=wildfly10
      language: java
      jdk: openjdk8
before_script:
  - bash ./travis/$OPENRASP_LANG/before_script.sh
script:
  - travis_retry bash ./travis/$OPENRASP_LANG/script.sh