cache:
  yarn: true
  directories:
    - $HOME/cache
    - $HOME/.m2
services:
  - mysql
  - postgresql
matrix:
  include:
    - env: OPENRASP_LANG=java SERVER=tomcat8
      language: java
      jdk: openjdk8
    - env: OPENRASP_LANG=java SERVER=jetty9
      language: java
      jdk: oraclejdk8
    - env: OPENRASP_LANG=java SERVER=tomcat6
      language: java
      jdk: openjdk7
    - env: OPENRASP_LANG=java SERVER=tomcat7
      language: java
      jdk: openjdk7
    - env: OPENRASP_LANG=java SERVER=jboss4
      language: java
      jdk: openjdk7
    - env: OPENRASP_LANG=java SERVER=jboss5
      language: java
      jdk: openjdk7
    - env: OPENRASP_LANG=java SERVER=jboss6
      language: java
      jdk: openjdk7
    - env: OPENRASP_LANG=java SERVER=springboot
      language: java
      jdk: openjdk7
    - env: OPENRASP_LANG=java SERVER=dubbo
      language: java
      jdk: openjdk7
    - env: OPENRASP_LANG=java SERVER=tomcat8-jdk11
      language: java
      jdk: oraclejdk11
before_script:
  - bash ./travis/$OPENRASP_LANG/before_script.sh
script:
  - travis_retry bash ./travis/$OPENRASP_LANG/script.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)  